server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/profile_db
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.github.client-id=Ov23liTlDFB5DPpaamPF
spring.security.oauth2.client.registration.github.client-secret=154c9e974052ad6114dadc4f6466fb259e3ebccb
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.registration.google.client-id=304811715477-p9sbsp52mbalc0eptrer6p4opsulg00e.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
